"""add razorpay order id column to orders

Revision ID: 0d6a79524fbe
Revises: 97294d3d263d
Create Date: 2024-05-05 21:56:12.295222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6a79524fbe'
down_revision: Union[str, None] = '97294d3d263d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rz_id', sa.String(), server_default='_', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rz_id')
    # ### end Alembic commands ###
